---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    fluxcd.io/tag.platform-website: regex:^sha-*
  name: project-discord-bot
  namespace: project-discord-bot
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: project-discord-bot
      containers:
      - $setElementOrder/env:
        - name: MAIN_GUILD
        - name: DISCORD_TOKEN
        - name: METRICS_PORT
        - name: API_PORT
        - name: BACKEND_MTLS_CERT
        - name: BACKEND_MTLS_KEY
        - name: BACKEND_CA
        env:
        - name: MAIN_GUILD
          value: "711687367081328752"
        image: devlaunchers/project_discord-bot:1.0.3
        name: project-discord-bot
