---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    fluxcd.io/tag.platform-website: regex:^sha-*
  name: project-discord-bot
  namespace: project-discord-bot
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: project-discord-bot
      containers:
      - image: devlaunchers/project_discord-bot:sha-4e6e310
        name: project-discord-bot
