apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: discord-bot
bases:
  - ../workload
images:
  - name: devlaunchers/project_discord-bot
    newName: devlaunchers/project_discord-bot
    newTag: d3407f8-202201111545 # {"$imagepolicy": "discord-bot:discord-bot:tag"}
