apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: discord-bot
bases:
  - ../workload
images:
- name: devlaunchers/project_discord-bot
  newName: devlaunchers/project_discord-bot
  newTag: a0ca8d5-202106191748 # {"$imagepolicy": "discord-bot:discord-bot:tag"}