apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discord-bot-pv-claim
  namespace: discord-bot
  labels:
    app: discord-bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi