version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "docker-start"]
    depends_on:
      - migrations
    migrations:
      image: discord-bot-migration
    env_file:
      - .env
    environment:
      - PORT=3000
      - BACKEND_MTLS_CERT=./dev/cert.pem
      - BACKEND_MTLS_KEY=./dev/key.key
