---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: project-discord-bot
  namespace: project-discord-bot
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: project-discord-bot
      containers:
      - image: devlaunchers/project_discord-bot:sha-5224592
        name: project-discord-bot
