---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    fluxcd.io/tag.project-discord-bot: semver:*
  name: project-discord-bot
  namespace: project-discord-bot
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: project-discord-bot
      containers:
      - image: devlaunchers/project_discord-bot:1.0.3
        name: project-discord-bot
      env:
        - name: DISCORD_BOT_POSTGRES_PORT
              value: "17792"
        - name: DISCORD_BOT_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: user
        - name: DISCORD_BOT_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: DISCORD_BOT_POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres
              key: hostname
        - name: DISCORD_BOT_POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres
              key: db
