---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: project-discord-bot
  namespace: project-discord-bot
  annotations:
    fluxcd.io/tag.project-discord-bot: semver:*
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: project-discord-bot
      containers:
      - image: devlaunchers/project_discord-bot:sha-df57861
        name: project-discord-bot
