apiVersion: v1
kind: Service
metadata:
  name: project-discord-bot
spec:
  selector:
    app: project-discord-bot
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: project-discord-bot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000