apiVersion: v1
kind: Service
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  selector:
    app: discord-bot
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: discord-bot
spec:
  selector:
    app: discord-bot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000