apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project-discord-bot
  name: project-discord-bot
  annotations:
    fluxcd.io/automated: "true"
  labels:
    app: project-discord-bot
spec:
  replicas: 1
  serviceName: project-discord-bot
  selector:
    matchLabels:
      app: project-discord-bot
  template:
    metadata:
      labels:
        app: project-discord-bot
    spec:
      containers:
        - name: project-discord-bot
          image: devlaunchers/project_discord-bot:latest
          ports:
            - containerPort: 3000
            - containerPort: 8000
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: project-discord-bot
                  key: discord-token
            - name: PORT
              value: "8000"
            - name: BACKEND_MTLS_CERT
              value: "/etc/tls/api-client.pem"
            - name: BACKEND_MTLS_KEY
              value: "/etc/tls/api-key.key"
            - name: BACKEND_CA
              value: "/etc/tls/backend-ca.pem"
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: project-discord-bot-storage
              mountPath: /usr/src/app/data
            - name: api-mtls
              # Mount 2 files, cert at /etc/tls/api-client.pem and key at /etc/tls/api-key.key
              mountPath: "/etc/tls"
              readOnly: true
      volumes:
        - name: project-discord-bot-storage
          persistentVolumeClaim:
            claimName: project-discord-bot-hostpath-pvc
        - name: api-mtls
          secret:
            secretName: tls
